### ISSUE TITLE
Shaders for iOS?

### ISSUE THREAD

**Issue by jonpchin** [TheMaverickProgrammer/SFML_ANDROID_ES_3#1]
Does this only work for Android or can shaders also work with iOS?

**Comment by TheMaverickProgrammer** [comment]
GL ES 2.0 should work on ios. I dont have a modern iOS phone to test however,

**Comment by jonpchin** [comment]
I will test it on iOS. It will be a while before I can start that task, maybe 4-5 months.

**Comment by TheMaverickProgrammer** [comment]
please let me know if you beat me to it! Feel free to open a new issue when you do. I'll close this one. Cheers.
