### ISSUE TITLE
fragment shader error

### ISSUE THREAD

**Issue by jonpchin** [TheMaverickProgrammer/SFML_ANDROID_ES_3#2]
Hi,

I am getting the following error when trying to run an android application that uses the SFML libraries that are built with the code from this repository.  I compiled the libraries from this repo using android ndk r16b. 

05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: Failed to compile fragment shader:
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: Fragment shader compilation failed.
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: ERROR: 0:7: 'gl_TexCoord' : undeclared identifier 
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: ERROR: 0:7: 'gl_TexCoord' :  left of '[' is not of type array, matrix, or vector  
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: ERROR: 0:7: 'xy' :  field selection requires structure, vector, or matrix on left hand side 
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: ERROR: 0:7: 'texture2D' : no matching overloaded function found 
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: ERROR: 0:7: '=' :  cannot convert from 'const float' to '4-component vector of float'
05-30 00:12:46.651 28843-29057/org.sfmldev.android I/sfml-error: ERROR: 5 compilation errors.  No code generated.

Any ideas on how to resolve these errors?

**Comment by jonpchin** [comment]
For reference here is one of the shader files I believe it is trying to compile:

uniform sampler2D texture;

uniform vec4 colorLight;

void main()
{
	gl_FragColor = texture2D(texture, gl_TexCoord[0].xy) * colorLight;

}

**Comment by TheMaverickProgrammer** [comment]
That is not a compatible shader program. ES has a programmable pipeline. It
looks like that is a much older version.

**Comment by jonpchin** [comment]
I am now getting this error with no other clues in the android logcat:

2021-06-10 08:35:03.299 8809-8848/org.sfmldev.android I/sfml-error: Failed to link shader:

I am loading a fragment shader using sf::Shader::loadFromFile. I believe I have not been able to load any of the shaders as that "Failed to link shader" error message is printed the exact number of times I call sf::Shader::loadFromFile.

**Comment by TheMaverickProgrammer** [comment]
your shaders are not compatible. It sounds to me you need to learn GLSL
https://github.com/mattdesl/lwjgl-basics/wiki/GLSL-Versions

reference this material and when you find a problem that cannot be solved by conventional means I can help you as long as you have descriptive errors.

at this time this is a GLSL misunderstanding and I cannot help you further.

I'll keep this issue open for you.

**Comment by jonpchin** [comment]
I believe I got everything to work. However there is a big performance issue (FPS drops from 60 to like 15-20). I commented out a window.draw call for drawing a bunch of sprites and the FPS went up to 60. So somewhere in the draw function from your experimental SFML android shader port there is a performance drop. Do you have any ideas on how to resolve this? The game is unplayable at 15-20 FPS.

**Comment by TheMaverickProgrammer** [comment]
Yeah SFML doesn't expose the render surface as a frame buffer object. I'm
constantly drawing to the texture, then reading from the pixel bytes on the
CPU, doing stuff with it, drawing again, etc. on every pass. Tuning off
shaders increases FPS but there's lots to be desired. I'm moving away from
SFML for this reason in the long term but I'd like to find some time this
year or next adding better frame buffer object support.

**Comment by jonpchin** [comment]
So one solution to resolve the low FPS is to add "frame buffer object support". How much work is involved in this?

Edit: If you can point me in the direction/resources in how to resolve this issue that would be great. I do not know on how to implement the solution you are talking about.

**Comment by TheMaverickProgrammer** [comment]
It'll be work. The best I can help is you need to google and learn OpenGL
frame buffer objects and find tutorials that do multiple shader passes on
the GPU.
